/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PagamentoRecusadoRouteImport } from './routes/pagamento-recusado'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento-pendente'
import { Route as PagamentoAprovadoRouteImport } from './routes/pagamento-aprovado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRecusadoRoute = PagamentoRecusadoRouteImport.update({
  id: '/pagamento-recusado',
  path: '/pagamento-recusado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pagamento-pendente',
  path: '/pagamento-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoAprovadoRoute = PagamentoAprovadoRouteImport.update({
  id: '/pagamento-aprovado',
  path: '/pagamento-aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pagamento-aprovado': typeof PagamentoAprovadoRoute
  '/pagamento-pendente': typeof PagamentoPendenteRoute
  '/pagamento-recusado': typeof PagamentoRecusadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pagamento-aprovado': typeof PagamentoAprovadoRoute
  '/pagamento-pendente': typeof PagamentoPendenteRoute
  '/pagamento-recusado': typeof PagamentoRecusadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/pagamento-aprovado': typeof PagamentoAprovadoRoute
  '/pagamento-pendente': typeof PagamentoPendenteRoute
  '/pagamento-recusado': typeof PagamentoRecusadoRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pagamento-aprovado'
    | '/pagamento-pendente'
    | '/pagamento-recusado'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pagamento-aprovado'
    | '/pagamento-pendente'
    | '/pagamento-recusado'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/pagamento-aprovado'
    | '/pagamento-pendente'
    | '/pagamento-recusado'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  PagamentoAprovadoRoute: typeof PagamentoAprovadoRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoRecusadoRoute: typeof PagamentoRecusadoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-recusado': {
      id: '/pagamento-recusado'
      path: '/pagamento-recusado'
      fullPath: '/pagamento-recusado'
      preLoaderRoute: typeof PagamentoRecusadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-pendente': {
      id: '/pagamento-pendente'
      path: '/pagamento-pendente'
      fullPath: '/pagamento-pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-aprovado': {
      id: '/pagamento-aprovado'
      path: '/pagamento-aprovado'
      fullPath: '/pagamento-aprovado'
      preLoaderRoute: typeof PagamentoAprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  PagamentoAprovadoRoute: PagamentoAprovadoRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoRecusadoRoute: PagamentoRecusadoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
